server:
 port: 9194
 
spring:
 datasource:
  username: root
  password: admin
  url: jdbc:mysql://localhost:3306/mental_db
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  show-sql: true
  hibernate: 
   ddl-auto: update
   format_sql: true
   properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
 servlet: 
  multipart: 
  max-file-size: 5MB
  max-request-size: 5MB
  file-size-threshold: 2MB   

logging:
 level:
  org:
   springframework:
    security: DEBUG

